# Generated by Django 5.2.3 on 2025-06-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'permissions': [('manage_all_users', 'مدیریت کامل کاربران'), ('access_all_data', 'دسترسی به تمام داده\u200cها'), ('system_settings', 'تنظیمات سیستم'), ('backup_restore', 'پشتیبان\u200cگیری و بازگردانی'), ('manage_customers', 'مدیریت مشتریان'), ('manage_orders', 'مدیریت سفارشات'), ('manage_inventory', 'مدیریت موجودی'), ('view_reports', 'مشاهده گزارش\u200cها'), ('manage_business_hours', 'مدیریت ساعات کاری'), ('manage_prices', 'مدیریت قیمت\u200cها'), ('manage_invoices', 'مدیریت فاکتورها'), ('view_financial_reports', 'گزارش\u200cهای مالی'), ('manage_payments', 'مدیریت پرداخت\u200cها'), ('export_financial_data', 'خروجی داده\u200cهای مالی'), ('view_own_orders', 'مشاهده سفارشات خود'), ('create_orders', 'ایجاد سفارش جدید'), ('view_own_profile', 'مشاهده پروفایل شخصی'), ('update_own_profile', 'ویرایش اطلاعات شخصی')], 'verbose_name': '👤 کاربر', 'verbose_name_plural': '👥 کاربران'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', '🔴 Super Admin'), ('admin', '🟡 Admin'), ('finance', '🟢 Finance'), ('customer', '🔵 Customer')], default='customer', help_text='نقش کاربر که سطح دسترسی او را تعیین می\u200cکند', max_length=20, verbose_name='🎭 نقش کاربری'),
        ),
    ]
