# Generated by Django 5.2.3 on 2025-06-28 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('location', models.CharField(choices=[('Anbar_Akhal', '📍 انبار آخال'), ('Anbar_Muhvateh_Kordan', '📍 انبار محوطه کردان'), ('Anbar_Khamir_Kordan', '📍 انبار کردان'), ('Anbar_Khamir_Ghadim', '📍 انبار خمیر قدیم'), ('Anbar_Koochak', '📍 انبار کوچک'), ('Anbar_Salon_Tolid', '📍 انبار سالن تولید'), ('Anbar_Sangin', '📍 انبار سنگین')], help_text='انبار محل نگهداری محصول', max_length=255, verbose_name='📍 مکان انبار')),
                ('status', models.CharField(choices=[('In-stock', '📦 موجود در انبار'), ('Sold', '💰 فروخته شده'), ('Pre-order', '⏳ پیش\u200cسفارش')], default='In-stock', help_text='وضعیت فعلی محصول در سیستم', max_length=50, verbose_name='📊 وضعیت محصول')),
                ('payment_status', models.CharField(choices=[('Cash', '💵 نقدی'), ('Pending', '⏳ در انتظار پرداخت')], default='Pending', help_text='وضعیت پرداخت محصول', max_length=50, verbose_name='💳 وضعیت پرداخت')),
                ('reel_number', models.CharField(help_text='شماره یکتای ریل محصول', max_length=255, unique=True, verbose_name='🏷️ شماره ریل')),
                ('width', models.IntegerField(help_text='عرض محصول به میلی\u200cمتر', verbose_name='📏 عرض (mm)')),
                ('gsm', models.IntegerField(help_text='وزن محصول به گرم بر متر مربع', verbose_name='⚖️ GSM (g/m²)')),
                ('length', models.IntegerField(help_text='طول محصول به متر', verbose_name='📐 طول (m)')),
                ('grade', models.CharField(help_text='درجه و کیفیت محصول', max_length=255, verbose_name='🏆 درجه کیفیت')),
                ('breaks', models.IntegerField(default=0, help_text='تعداد شکستگی\u200cهای موجود در محصول', verbose_name='💔 تعداد شکستگی')),
                ('qr_code', models.TextField(blank=True, help_text='کد QR مرتبط با محصول برای ردیابی سریع', null=True, verbose_name='📱 کد QR')),
            ],
            options={
                'verbose_name': '📦 محصول',
                'verbose_name_plural': '📦 محصولات',
                'db_table': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reel_number'], name='Products_reel_nu_f2c879_idx'), models.Index(fields=['location'], name='Products_locatio_5a20a5_idx'), models.Index(fields=['status'], name='Products_status_6f3eea_idx'), models.Index(fields=['payment_status'], name='Products_payment_eb8ccb_idx'), models.Index(fields=['width', 'gsm'], name='Products_width_a1a9e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('action', models.CharField(choices=[('CREATE', '✅ ایجاد'), ('UPDATE', '📝 ویرایش'), ('DELETE', '🗑️ حذف'), ('VIEW', '👁️ مشاهده'), ('LOGIN', '🔑 ورود'), ('LOGOUT', '🚪 خروج'), ('EXPORT', '📤 خروجی'), ('IMPORT', '📥 ورودی'), ('APPROVE', '✅ تایید'), ('REJECT', '❌ رد'), ('PAYMENT', '💰 پرداخت'), ('ORDER', '🛒 سفارش'), ('DELIVERY', '🚚 تحویل'), ('CANCEL', '🚫 لغو'), ('RESTORE', '♻️ بازگردانی'), ('BACKUP', '💾 پشتیبان\u200cگیری'), ('ERROR', '⚠️ خطا'), ('WARNING', '⚡ هشدار'), ('INFO', 'ℹ️ اطلاعات')], help_text='نوع عملیات انجام شده توسط کاربر', max_length=20, verbose_name='🎭 نوع عملیات')),
                ('description', models.TextField(help_text='توضیحات کامل عملیات انجام شده', verbose_name='📝 توضیحات')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='آدرس IP کاربر در زمان انجام عملیات', null=True, verbose_name='🌐 آدرس IP')),
                ('user_agent', models.TextField(blank=True, help_text='اطلاعات مرورگر و سیستم\u200cعامل کاربر', null=True, verbose_name='🖥️ اطلاعات مرورگر')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی مرتبط با عملیات (JSON format)', verbose_name='📄 اطلاعات اضافی')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='🆔 شناسه آبجکت')),
                ('severity', models.CharField(choices=[('LOW', '🟢 کم'), ('MEDIUM', '🟡 متوسط'), ('HIGH', '🟠 بالا'), ('CRITICAL', '🔴 بحرانی')], default='LOW', help_text='سطح اهمیت این لاگ', max_length=10, verbose_name='⚠️ سطح اهمیت')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='🔗 نوع محتوا')),
                ('user', models.ForeignKey(blank=True, help_text='کاربری که این عملیات را انجام داده است', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='👤 کاربر')),
            ],
            options={
                'verbose_name': '📜 لاگ فعالیت',
                'verbose_name_plural': '📜 لاگ\u200cهای فعالیت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action'], name='core_activi_user_id_f3082a_idx'), models.Index(fields=['action', 'severity'], name='core_activi_action_e70838_idx'), models.Index(fields=['created_at'], name='core_activi_created_5c6490_idx'), models.Index(fields=['content_type', 'object_id'], name='core_activi_content_1a7154_idx')],
            },
        ),
    ]
