# Generated by Django 5.2.3 on 2025-06-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_orderitem_order_core_order_order_n_6d2664_idx_and_more'),
    ]

    operations = [
        # Remove payment_status index from Product model first
        migrations.RemoveIndex(
            model_name='product',
            name='Products_payment_eb8ccb_idx',
        ),
        # Then remove payment_status field from Product model
        migrations.RemoveField(
            model_name='product',
            name='payment_status',
        ),
    ]
