# Generated by Django 5.2.3 on 2025-07-01 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_add_logs_field_to_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('tracking_code', models.CharField(help_text='شماره پیگیری منحصر به فرد پرداخت', max_length=100, unique=True, verbose_name='🏷️ کد پیگیری')),
                ('amount', models.DecimalField(decimal_places=0, help_text='مبلغ پرداخت به ریال', max_digits=15, verbose_name='💰 مبلغ (ریال)')),
                ('display_amount', models.DecimalField(decimal_places=0, help_text='مبلغ نمایشی به تومان', max_digits=15, verbose_name='💵 مبلغ نمایشی (تومان)')),
                ('gateway', models.CharField(choices=[('zarinpal', '💎 زرین\u200cپال'), ('shaparak', '🏦 شاپرک'), ('mellat', '🟢 ملت'), ('parsian', '🔵 پارسیان'), ('pasargad', '🟡 پاسارگاد'), ('saderat', '🟠 صادرات')], help_text='درگاه پرداخت انتخابی', max_length=20, verbose_name='🌐 درگاه پرداخت')),
                ('status', models.CharField(choices=[('INITIATED', '🟡 آغاز شده'), ('REDIRECTED', '🔄 هدایت شده'), ('PENDING', '⏳ در انتظار پرداخت'), ('PROCESSING', '🔄 در حال پردازش'), ('VERIFYING', '🔍 در حال تایید'), ('SUCCESS', '✅ موفق'), ('FAILED', '❌ ناموفق'), ('CANCELLED', '🚫 لغو شده'), ('TIMEOUT', '⏰ منقضی شده'), ('REFUNDED', '💸 بازگشت داده شده'), ('PARTIALLY_REFUNDED', '💰 بازگشت جزئی'), ('DISPUTED', '⚖️ مورد اختلاف'), ('ERROR', '⚠️ خطا')], default='INITIATED', help_text='وضعیت فعلی پرداخت', max_length=20, verbose_name='📊 وضعیت پرداخت')),
                ('payment_type', models.CharField(choices=[('FULL', '💰 پرداخت کامل'), ('PARTIAL', '💵 پرداخت جزئی'), ('INSTALLMENT', '�� قسطی')], default='FULL', help_text='نوع پرداخت (کامل/جزئی/قسطی)', max_length=20, verbose_name='💳 نوع پرداخت')),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='شماره تراکنش ارائه شده توسط درگاه', max_length=200, null=True, verbose_name='🆔 شماره تراکنش درگاه')),
                ('bank_reference_number', models.CharField(blank=True, help_text='شماره مرجع ارائه شده توسط بانک', max_length=200, null=True, verbose_name='🏦 شماره مرجع بانک')),
                ('masked_card_number', models.CharField(blank=True, help_text='شماره کارت ماسک شده (مثال: ****-****-****-1234)', max_length=20, null=True, verbose_name='💳 شماره کارت (ماسک)')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='آدرس IP کاربر در زمان پرداخت', null=True, verbose_name='🌐 IP کاربر')),
                ('user_agent', models.TextField(blank=True, help_text='اطلاعات مرورگر و سیستم\u200cعامل کاربر', null=True, verbose_name='🖥️ اطلاعات مرورگر')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='زمان شروع فرآیند پرداخت', verbose_name='📅 زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, help_text='زمان اتمام یا لغو پرداخت', null=True, verbose_name='📅 زمان اتمام')),
                ('expires_at', models.DateTimeField(blank=True, help_text='زمان انقضای جلسه پرداخت', null=True, verbose_name='⏰ زمان انقضا')),
                ('gateway_data', models.JSONField(blank=True, default=dict, help_text='اطلاعات اضافی دریافتی از درگاه (JSON)', verbose_name='📄 داده\u200cهای درگاه')),
                ('error_message', models.TextField(blank=True, help_text='پیام خطا در صورت عدم موفقیت پرداخت', null=True, verbose_name='📝 پیام خطا')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='تعداد تلاش\u200cهای انجام شده برای پرداخت', verbose_name='🔄 تعداد تلاش')),
                ('payer_phone', models.CharField(blank=True, help_text='شماره تلفن فرد پرداخت\u200cکننده', max_length=15, null=True, verbose_name='📱 شماره تلفن پرداخت\u200cکننده')),
                ('payer_email', models.EmailField(blank=True, help_text='ایمیل فرد پرداخت\u200cکننده', max_length=254, null=True, verbose_name='📧 ایمیل پرداخت\u200cکننده')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی درباره پرداخت', verbose_name='📝 توضیحات')),
                ('logs', models.TextField(blank=True, help_text='لاگ\u200cهای کامل فرآیند پرداخت', verbose_name='📝 لاگ\u200cهای پرداخت')),
                ('order', models.ForeignKey(help_text='سفارش مرتبط با این پرداخت', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order', verbose_name='🛒 سفارش')),
                ('user', models.ForeignKey(blank=True, help_text='کاربری که پرداخت را انجام می\u200cدهد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='👤 کاربر')),
            ],
            options={
                'verbose_name': '💳 پرداخت',
                'verbose_name_plural': '💳 پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('callback_type', models.CharField(choices=[('VERIFY', '✅ تایید پرداخت'), ('RETURN', '🔙 بازگشت کاربر'), ('WEBHOOK', '🔗 وب\u200cهوک'), ('ERROR', '⚠️ خطا')], help_text='نوع کال\u200cبک دریافتی', max_length=20, verbose_name='📞 نوع کال\u200cبک')),
                ('raw_data', models.JSONField(default=dict, help_text='داده\u200cهای خام دریافتی از درگاه', verbose_name='📄 داده\u200cهای خام')),
                ('sender_ip', models.GenericIPAddressField(blank=True, help_text='آدرس IP ارسال\u200cکننده کال\u200cبک', null=True, verbose_name='🌐 IP ارسال\u200cکننده')),
                ('response_message', models.TextField(blank=True, help_text='پیام پاسخ ارسال شده به درگاه', verbose_name='📝 پیام پاسخ')),
                ('is_processed', models.BooleanField(default=False, help_text='آیا این کال\u200cبک با موفقیت پردازش شده است؟', verbose_name='✅ پردازش شده')),
                ('payment', models.ForeignKey(help_text='پرداخت مرتبط با این کال\u200cبک', on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='payments.payment', verbose_name='💳 پرداخت')),
            ],
            options={
                'verbose_name': '📞 کال\u200cبک پرداخت',
                'verbose_name_plural': '📞 کال\u200cبک\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('refund_amount', models.DecimalField(decimal_places=0, help_text='مبلغ بازگشت وجه به ریال', max_digits=15, verbose_name='💰 مبلغ بازگشت (ریال)')),
                ('status', models.CharField(choices=[('INITIATED', '🟡 درخواست شده'), ('PROCESSING', '🔄 در حال پردازش'), ('SUCCESS', '✅ موفق'), ('FAILED', '❌ ناموفق'), ('CANCELLED', '🚫 لغو شده')], default='INITIATED', max_length=20, verbose_name='📊 وضعیت بازگشت وجه')),
                ('refund_transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='🆔 شماره تراکنش بازگشت')),
                ('reason', models.TextField(help_text='دلیل درخواست بازگشت وجه', verbose_name='📝 دلیل بازگشت وجه')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='📅 زمان تکمیل')),
                ('payment', models.ForeignKey(help_text='پرداخت اصلی که بازگشت وجه آن درخواست شده', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='💳 پرداخت اصلی')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='👤 درخواست\u200cکننده')),
            ],
            options={
                'verbose_name': '💸 بازگشت وجه',
                'verbose_name_plural': '💸 بازگشت\u200cهای وجه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tracking_code'], name='payments_pa_trackin_1d280e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_transaction_id'], name='payments_pa_gateway_2a3159_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway'], name='payments_pa_gateway_dc3f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='payments_pa_order_i_1d1c93_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user'], name='payments_pa_user_id_be07d0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['started_at'], name='payments_pa_started_14ea62_idx'),
        ),
    ]
