# Generated by Django 5.2.3 on 2025-06-28 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='قیمت محصول به تومان - فقط Super Admin می\u200cتواند تغییر دهد', max_digits=15, verbose_name='💰 قیمت (تومان)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, help_text='زمان آخرین تغییر قیمت توسط Super Admin', null=True, verbose_name='📅 آخرین تغییر قیمت'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_updated_by',
            field=models.ForeignKey(blank=True, help_text='کاربری که آخرین بار قیمت را تغییر داده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_prices', to=settings.AUTH_USER_MODEL, verbose_name='👤 تغییر قیمت توسط'),
        ),
        migrations.AlterField(
            model_name='product',
            name='payment_status',
            field=models.CharField(choices=[('Cash', '💵 نقدی'), ('Pending', '⏳ قسطی')], default='Pending', help_text='وضعیت پرداخت محصول', max_length=50, verbose_name='💳 وضعیت پرداخت'),
        ),
    ]
