# Generated by Django 5.2.3 on 2025-06-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activitylog_action_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_method',
            field=models.CharField(choices=[('Cash', '💵 نقدی'), ('Terms', '📅 قسطی'), ('Bank_Transfer', '🏦 حواله بانکی'), ('Check', '📝 چک')], default='Cash', help_text='نوع پرداخت انتخابی برای این محصول', max_length=20, verbose_name='💳 نوع پرداخت'),
        ),
    ]
