# Generated by Django 5.2.3 on 2025-06-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_payment_method_to_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', '✅ فعال'), ('Inactive', '⏸️ غیرفعال'), ('Suspended', '🚫 معلق'), ('Blocked', '🔒 مسدود')], default='Active', help_text='وضعیت فعلی مشتری در سیستم', max_length=255, verbose_name='📊 وضعیت مشتری'),
        ),
    ]
