# Generated by Django 5.2.3 on 2025-06-30 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_customer_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='set_by',
            field=models.ForeignKey(blank=True, help_text='کاربری که ساعات کاری را تنظیم کرده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_working_hours', to=settings.AUTH_USER_MODEL, verbose_name='👑 تنظیم\u200cکننده'),
        ),
    ]
