# Generated by Django 5.2.3 on 2025-06-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_unique_customer_name_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logs',
            field=models.TextField(blank=True, default='', help_text='لاگ\u200cهای تحلیلی برای تیم آنالیتیکس (append only)', verbose_name='📝 لاگ\u200cها'),
        ),
    ]
