# Generated by Django 5.2.3 on 2025-07-03 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_logs_field_to_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=0, max_length=255, verbose_name='نوع کاغذ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('cash', '💵 خرید نقدی'), ('credit', '📃 خرید نسیه')], default='cash', help_text='نقدی یا نسیه بودن محصول', max_length=10, verbose_name='نوع فروش'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=0, max_length=100, verbose_name='اندازه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', '💵 نقدی'), ('Terms', '📅 قسطی')], help_text='روش پرداخت انتخاب شده توسط مشتری', max_length=20, verbose_name='💳 روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='payment_method',
            field=models.CharField(choices=[('Cash', '💵 نقدی'), ('Terms', '📅 قسطی')], default='Cash', help_text='نوع پرداخت انتخابی برای این محصول', max_length=20, verbose_name='💳 نوع پرداخت'),
        ),
        migrations.CreateModel(
            name='PriceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('cash_price', models.DecimalField(decimal_places=2, default=0.0, help_text='قیمت نقدی کلی برای محصولات - فقط Super Admin می\u200cتواند تغییر دهد', max_digits=15, verbose_name='💰 قیمت نقدی (تومان)')),
                ('terms_price', models.DecimalField(decimal_places=2, default=0.0, help_text='قیمت نسیه کلی برای محصولات - فقط Super Admin می\u200cتواند تغییر دهد', max_digits=15, verbose_name='📅 قیمت نسیه (تومان)')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این تنظیمات قیمت فعال است؟', verbose_name='✅ فعال')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی درباره تنظیمات قیمت', verbose_name='📝 توضیحات')),
                ('cash_price_updated_at', models.DateTimeField(blank=True, help_text='زمان آخرین تغییر قیمت نقدی', null=True, verbose_name='📅 آخرین تغییر قیمت نقدی')),
                ('terms_price_updated_at', models.DateTimeField(blank=True, help_text='زمان آخرین تغییر قیمت نسیه', null=True, verbose_name='📅 آخرین تغییر قیمت نسیه')),
                ('set_by', models.ForeignKey(blank=True, help_text='کاربری که قیمت\u200cها را تنظیم کرده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_price_settings', to=settings.AUTH_USER_MODEL, verbose_name='👑 تنظیم\u200cکننده')),
            ],
            options={
                'verbose_name': '💰 تنظیمات قیمت',
                'verbose_name_plural': '💰 تنظیمات قیمت\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='core_prices_is_acti_f0681a_idx'), models.Index(fields=['cash_price', 'terms_price'], name='core_prices_cash_pr_61c342_idx')],
            },
        ),
    ]
