# Generated by Django 5.2.3 on 2025-06-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('status', models.CharField(blank=True, default='Active', help_text='وضعیت فعلی مشتری در سیستم (Active, Inactive, Suspended)', max_length=255, verbose_name='📊 وضعیت مشتری')),
                ('customer_name', models.CharField(help_text='نام کامل یا نام شرکت مشتری (اجباری)', max_length=255, verbose_name='👤 نام مشتری')),
                ('address', models.TextField(blank=True, help_text='آدرس کامل محل سکونت یا کسب\u200cوکار مشتری', verbose_name='🏠 آدرس')),
                ('phone', models.CharField(blank=True, help_text='شماره تلفن تماس مشتری (همراه یا ثابت)', max_length=20, verbose_name='📞 شماره تلفن')),
                ('comments', models.TextField(blank=True, help_text='یادداشت\u200cها و توضیحات اضافی درباره مشتری', verbose_name='💬 توضیحات')),
                ('economic_code', models.CharField(blank=True, help_text='کد اقتصادی شرکت یا کسب\u200cوکار مشتری برای صدور فاکتور رسمی', max_length=15, null=True, verbose_name='💼 کد اقتصادی خریدار')),
                ('postcode', models.CharField(blank=True, help_text='کد پستی ده رقمی آدرس مشتری', max_length=10, null=True, verbose_name='📮 کد پستی خریدار')),
                ('national_id', models.CharField(blank=True, help_text='شناسه ملی (اشخاص حقیقی) یا شناسه اقتصادی (اشخاص حقوقی)', max_length=50, null=True, verbose_name='🆔 شناسه ملی خریدار')),
            ],
            options={
                'verbose_name': '👤 مشتری',
                'verbose_name_plural': '👥 مشتریان',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_name'], name='core_custom_custome_28997a_idx'), models.Index(fields=['phone'], name='core_custom_phone_cf7ec3_idx'), models.Index(fields=['national_id'], name='core_custom_nationa_958848_idx'), models.Index(fields=['status'], name='core_custom_status_c5c22d_idx')],
            },
        ),
    ]
