# Generated by Django 5.2.3 on 2025-06-28 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_price_product_price_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('order_number', models.CharField(help_text='شماره یکتای سفارش', max_length=50, unique=True, verbose_name='🏷️ شماره سفارش')),
                ('status', models.CharField(choices=[('Pending', '⏳ در انتظار تایید'), ('Confirmed', '✅ تایید شده'), ('Processing', '🔄 در حال پردازش'), ('Ready', '📦 آماده تحویل'), ('Delivered', '🚚 تحویل داده شده'), ('Cancelled', '❌ لغو شده'), ('Returned', '↩️ مرجوع شده')], default='Pending', help_text='وضعیت فعلی سفارش', max_length=20, verbose_name='📊 وضعیت سفارش')),
                ('payment_method', models.CharField(choices=[('Cash', '💵 نقدی'), ('Terms', '📅 قسطی'), ('Bank_Transfer', '🏦 حواله بانکی'), ('Check', '📝 چک')], help_text='روش پرداخت انتخاب شده توسط مشتری', max_length=20, verbose_name='💳 روش پرداخت')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='مبلغ کل سفارش به تومان', max_digits=15, verbose_name='💰 مبلغ کل (تومان)')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='درصد تخفیف اعمال شده', max_digits=5, verbose_name='🎯 تخفیف (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='مبلغ تخفیف به تومان', max_digits=15, verbose_name='💸 مبلغ تخفیف (تومان)')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='مبلغ نهایی پس از اعمال تخفیف', max_digits=15, verbose_name='💵 مبلغ نهایی (تومان)')),
                ('notes', models.TextField(blank=True, help_text='توضیحات و یادداشت\u200cهای مربوط به سفارش', verbose_name='📝 توضیحات')),
                ('delivery_address', models.TextField(blank=True, help_text='آدرس تحویل سفارش (در صورت تفاوت با آدرس مشتری)', verbose_name='🚚 آدرس تحویل')),
                ('expected_delivery_date', models.DateTimeField(blank=True, help_text='تاریخ تحویل مورد انتظار سفارش', null=True, verbose_name='📅 تاریخ تحویل مورد انتظار')),
                ('actual_delivery_date', models.DateTimeField(blank=True, help_text='تاریخ تحویل واقعی سفارش', null=True, verbose_name='📅 تاریخ تحویل واقعی')),
                ('created_by', models.ForeignKey(blank=True, help_text='کاربری که سفارش را ایجاد کرده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='👤 ایجادکننده')),
                ('customer', models.ForeignKey(help_text='مشتری سفارش\u200cدهنده', on_delete=django.db.models.deletion.CASCADE, to='core.customer', verbose_name='👤 مشتری')),
            ],
            options={
                'verbose_name': '🛒 سفارش',
                'verbose_name_plural': '🛒 سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='تعداد محصول درخواستی', verbose_name='🔢 تعداد')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='قیمت واحد محصول در زمان سفارش', max_digits=15, verbose_name='💰 قیمت واحد (تومان)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='قیمت کل این آیتم (تعداد × قیمت واحد)', max_digits=15, verbose_name='💵 قیمت کل (تومان)')),
                ('notes', models.TextField(blank=True, help_text='توضیحات خاص این آیتم', verbose_name='📝 توضیحات')),
                ('order', models.ForeignKey(help_text='سفارش مربوط به این آیتم', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.order', verbose_name='🛒 سفارش')),
                ('product', models.ForeignKey(help_text='محصول انتخاب شده', on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='📦 محصول')),
            ],
            options={
                'verbose_name': '📦 آیتم سفارش',
                'verbose_name_plural': '📦 آیتم\u200cهای سفارش',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='core_order_order_n_6d2664_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='core_order_custome_7ac3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='core_order_status_6fe5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method'], name='core_order_payment_ddc40b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='core_order_created_912d27_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='core_orderi_order_i_267c14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
