# Generated by Django 5.2.3 on 2025-06-28 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250628_1632'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', '✅ ایجاد'), ('UPDATE', '📝 ویرایش'), ('DELETE', '🗑️ حذف'), ('VIEW', '👁️ مشاهده'), ('LOGIN', '🔑 ورود'), ('LOGOUT', '🚪 خروج'), ('EXPORT', '📤 خروجی'), ('IMPORT', '📥 ورودی'), ('APPROVE', '✅ تایید'), ('REJECT', '❌ رد'), ('PAYMENT', '💰 پرداخت'), ('ORDER', '🛒 سفارش'), ('DELIVERY', '🚚 تحویل'), ('CANCEL', '🚫 لغو'), ('RESTORE', '♻️ بازگردانی'), ('BACKUP', '💾 پشتیبان\u200cگیری'), ('PRICE_UPDATE', '💰 تغییر قیمت'), ('ERROR', '⚠️ خطا'), ('WARNING', '⚡ هشدار'), ('INFO', 'ℹ️ اطلاعات')], help_text='نوع عملیات انجام شده توسط کاربر', max_length=20, verbose_name='🎭 نوع عملیات'),
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='📅 تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='تاریخ و زمان آخرین به\u200cروزرسانی رکورد به صورت خودکار ثبت می\u200cشود', verbose_name='🔄 تاریخ به\u200cروزرسانی')),
                ('start_time', models.TimeField(default='09:00', help_text='زمان شروع ساعات کاری (مثال: 09:00)', verbose_name='⏰ زمان شروع کار')),
                ('end_time', models.TimeField(default='18:00', help_text='زمان پایان ساعات کاری (مثال: 18:00)', verbose_name='🕐 زمان پایان کار')),
                ('description', models.TextField(blank=True, help_text='توضیحات اضافی درباره ساعات کاری', verbose_name='📝 توضیحات')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این ساعت کاری فعال است؟', verbose_name='✅ فعال')),
                ('set_by', models.ForeignKey(blank=True, help_text='Super Admin که این ساعات کاری را تنظیم کرده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_working_hours', to=settings.AUTH_USER_MODEL, verbose_name='👑 تنظیم شده توسط')),
            ],
            options={
                'verbose_name': '⏰ ساعات کاری',
                'verbose_name_plural': '⏰ ساعات کاری',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='core_workin_is_acti_1dceb9_idx'), models.Index(fields=['start_time', 'end_time'], name='core_workin_start_t_d6c8c4_idx')],
            },
        ),
    ]
